services:
    devcontainer:
        depends_on:
            - web-dev
        build:
            dockerfile: devcontainer.DockerFile
        restart: always
        command: sleep infinity
        volumes:
            - ../:/app/:cached
            - npm-cache:/home/vscode/.npm
    web-dev:
        image: nginxinc/nginx-unprivileged:1.29-alpine
        restart: unless-stopped
        ports:
            - '${PORT_LOCAL:-8000}:80'
        volumes:
            - ./web-dev.conf:/etc/nginx/conf.d/default.conf
            - ../dist/:/app/

volumes:
    npm-cache:
        external: true
