# This workflow will do a clean installation of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
    push:
    pull_request:
        branches: [main]
jobs:
    basic-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Use Node.js 26.x
              uses: actions/setup-node@v6
              with:
                  node-version: 26.x
                  cache: 'npm'
            - run: npm ci
            - name: cache
              uses: actions/cache/restore@v6
              with:
                  path: .cache
                  key: cache
            - run: make build--schema build--cache build--index
            - run: make lint ci--basic-checks
            - name: cache
              uses: actions/cache/restore@v6
              with:
                  path: .cache
                  key: cache
    coverage:
        # disabling this for now
        if: false
        needs: basic-checks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Use Node.js 26.x
              uses: actions/setup-node@v6
              with:
                  node-version: 26.x
                  cache: 'npm'
            - run: npm ci
            - name: Generate coverage
              run: make coverage--lcov
            - name: Coveralls GitHub Action
              uses: coverallsapp/github-action@v2.2.3
              with:
                  file: './coverage/lcov.info'
